###Login User & token
### L
POST http://localhost:4115/auth/login 
Content-Type: application/json

{
  "email": "Xzigyu@yopmail.com",
    "password": "passWord"
}

### Check token details verifying atuh token verification
GET http://localhost:4115/auth/check-details 
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjNjJmMDA2MC0zYzRmLTRmY2UtODk0MC1mM2Q5Y2IwNzA1MTQiLCJlbWFpbCI6Ilh6aWd5dUB5b3BtYWlsLmNvbSIsImlhdCI6MTcxOTQwNTg5NCwiZXhwIjoxNzE5NDA5NDk0fQ.0yOEcD4nlh3KvZFzX2rI-LI9LNQW7oZmA1LVSdY6wug