###Login User & token
### L
POST http://localhost:4115/auth/login 
Content-Type: application/json

{
      "email": "johndoes@yopmail.com",
    "password": "passWord"
}

### Check token details verifying atuh token verification
GET http://localhost:4115/auth/check-details 
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3OTQ4NWNiMi0yNTliLTRlODEtODkzMy01YzMxNzMyYzZlMzIiLCJlbWFpbCI6ImpvaG5kb2VzQHlvcG1haWwuY29tIiwiaWF0IjoxNzE5MDQ5NDU3LCJleHAiOjE3MTkwNTMwNTd9.VRckOfP5FamPxFu-BNYJAr86iq5DO63BqC-qIsU5UCM