###Login User & token
### L
POST http://localhost:4115/auth/login 
Content-Type: application/json

{
  "email": "Xzigyu@yopmail.com",
    "password": "passWord"
}

### Check token details verifying atuh token verification
GET http://localhost:4115/auth/check-details 
Content-Type: application/json
token:eyJbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4Y2Y4ZmMzMi0wYjVmLTRmMWMtODMxYy04Y2QxOTZhNTEyNjQiLCJlbWFpbCI6ImtlbkB5b3BtYWlsLmNvbSIsImlhdCI6MTcxOTI3MjE1MywiZXhwIjoxNzE5Mjc1NzUzfQ.DfJ4h2IR6JCjk4kIeAhjtETrMTqfj6DI_kVIA8ToPBw