###register User
POST http://localhost:4115/user/register
Content-Type: application/json

{           
    "firstname": "Xzing",
    "lastname": "Wang",
    "email": "Xzigyu@yopmail.com",
    "password": "passWord"

}



### All users
GET http://localhost:4115/user/all




###HARD Delete DANGER! User
DELETE http://localhost:4115/user/delete/9442680d-e24b-4319-b5ed-92b7729181f2




###soft deleteuser
PUT http://localhost:4115/user/softdelete/c62f0060-3c4f-4fce-8940-f3d9cb070514

###restore user
PUT http://localhost:4115/user/restore/c62f0060-3c4f-4fce-8940-f3d9cb070514





###Update user
PUT http://localhost:4115/user/update/1fd73e47-380b-4d5e-a3c7-4d84a422f30c
Content-Type: application/json

{
    "firstname": "Johnie",
    "lastname": "Doe",
    "email": "JOHMAIL@gmail.om",
    "password": "passswad",
    "profileImage": "imageuRL"
}



###userS Count
GET http://localhost:4115/user/count





###single user by id
GET http://localhost:4115/user/1fd73e47-380b-4d5e-a3c7-4d84a422f30c